now we can use <display> property
thodubois/react-native-woodpicker pull request #40
Opened 2021-05-21 12:20 UTC by PavelDikiy

It all started over 14 IOS

2021-05-21 12:27 UTC, thodubois commented
Wow, thanks for your PR. I'll take a look asap.

2021-05-21 13:09 UTC, PavelDikiy commented
and need update dependencies for picker 
https://www.npmjs.com/package/@react-native-community/picker - deprecated
https://github.com/react-native-picker/picker - new

2021-05-24 07:47 UTC, thodubois commented on .gitignore
> +yarn.lock
I don't think it's necessary to remove yarn.lock

2021-05-24 07:50 UTC, thodubois requested changes
Just remove the yarn.lock from gitignore or maybe I am missing something about it.  And I will merge it

2021-05-24 08:04 UTC, thodubois approved these changes

2021-05-24 08:35 UTC, PavelDikiy commented
i removed the yarn.lock from gitignore

2021-05-24 08:58 UTC, merged

2021-05-25 08:39 UTC, PavelDikiy commented
we forgot to update the version (0.2.8 => 0.2.9)

2021-05-25 14:38 UTC, thodubois commented
Hi, I pushed a new version, typescript compatible with your change. Some props might have change. Don't hesitate to tell if something is missing.